import type { Newsletter } from "../types/newsletter"

export const newsletter: Newsletter[] = [
    {
        title: 'DESENVOLVIMENTO E ESTAGNAÇÃO NA AMÉRICA LATINA: UMA ABORDAGEM ESTRUTURALISTA, POR CELSO FURTADO',
        category: 'Resenha',
        date: '2023-08-15',
         text: [
            'Em seu intitulado desenvolvimento e estagnação na América Latina, Celso Furtado busca compreender a partir de uma perspectiva estruturalista, como se deu historicamente o processo de estagnação do desenvolvimento das economias latino-americanas desde a forma como seus territórios foram colonizados até o modo em que buscaram a sua independência. Nesse sentido, o ponto-guia escolhido pelo autor do por que estudar esse tema dar-se-á por dois problemas: a tendência ao crescimento de preços nos produtos dessas economias e o decrescimento da renda per capita nas mesmas.',
            'Historicamente, o processo de colonização dos países latino-americanos foi sustentado por uma cadeia de núcleos urbanos melhor desenvolvidos e que buscavam em novas terras um lugar para auferirem ainda mais privilégios dentro de seu próprio espaço. Desse modo, os núcleos, por meio de concessões bem divididas dessas terras, àqueles que possuíam algum capital próprio para investirem na terra, principalmente em atividades agrícolas. Esses, agora proprietários da terra, após a abolição da escravatura, mantiveram em suas posses o modelo econômico chamado semifeudalismo, onde os servos produziam em suas terras e parte do que produziam era para sua própria subsistência por meio do aluguel de terras, e os seus donos exportavam os excedentes produzidos.',
            'Esse modelo semifeudal abriu brechas para o aparecimento de uma nova classe social oriunda daqueles que viram a oportunidade de lucrar por fora do setor agrário, contrabandeando pedras preciosas. Esses senhores tinham o interesse de exportá-las e dessa forma obterem seus ganhos, eles são o que a posteriori é compreendido como pré-capitalistas e tinham tendências à formação de centros urbanos, pois queriam que a terra se parecesse com o núcleo que a priori colonizou a terra.',
            'É importante notar que essas duas classes não são conflitantes apesar de tudo. Os latifundiários ocupavam-se da ordem no campo, tinham a propriedade em seu poder, possuíam o aluguel de terras, adicionados à créditos que possuíam para seus negócios advindos das metrópoles e núcleos que os dera as terras para investirem segundo seus interesses, enquanto àqueles que não tinham onde viver, trabalhavam para ter onde dormir e o que comer. Já os contrabandistas, beneficiavam-se da exportação de pedras e arrecadavam impostos sobre tais, pois com o aumento das oportunidades nas cidades, os trabalhadores saíam de suas terras a fim de melhores condições, lá encontram trabalho e os exportadores têm praticamente “mão de obra ilimitada” pelo fato de que, nos campos, quanto maior a família, mais trabalhadores.',
            'Com o surgimento do Estado próprio dessas colônias, há então a conformidade de interesses dessas duas classes. Os latifundiários querendo aumentar cada vez mais seus privilégios e direitos de propriedade, e os contrabandistas enfim legitimaram seus impérios sombrios com um novo nome: comerciantes.',
            'Logo após a introdução dos agentes, o autor descreve como se deu esse passo no setor exportador nos países latino-americanos. Sendo o que ele chama de: convergência de fatores exógenos e endógenos. Por endógenos, entende-se um fator que vem de dentro do território, ou seja, os metais e pedras minerados; as plantações; a pecuária etc. Já por exógenos, ele refere-se a fatores que surgem de fora, como os empréstimos concedidos pelas metrópoles. Nesse período, os latifundiários foram deixando de ser simplesmente representantes da Metrópole e passaram a ser uma instituição básica da estrutura social e política de suas próprias regiões. Ressalta-se que, em nenhum momento, os atores endógenos, latifundiários e comerciantes deixam de sobrepor os interesses da metrópole, pois esta é quem garantia a lucratividade para ambos.',
            'Ademais, o processo por trás da industrialização na América Latina ocorreu por meio da substituição de importações, onde a importação de determinados bens foi reduzida ou substituída no mercado interno por produtos produzidos internamente enquanto ampliou a importação de capital industrial afim do país obter meios pelos quais desenvolver a sua produção e deixar de exportar bens de menor valor agregado.',
            'Furtado deu o exemplo de: se um país, em 1929, possuía exportações que representavam cerca de 60% do fornecimento agregado de produtos manufaturados, com a redução dos preços de exportação, a capacidade de importação foi reduzida à 50%. Porém, sendo as exportações consistentes em produtos agrícolas e dizem respeito a um grande número de produtores, essa situação leva o governo a expandir o crédito para financiar a estocagem de excedentes agrícolas, bem como modificar a taxa de câmbio em favor dos exportadores de maneira a livrar o setor do excesso de oferta criado pela crise.',
            'Essas medidas permitiram que o nível de renda monetária do setor exportador tenho sido mantido estável e a demanda agregada ajustada a um nível maior de impostos concedidos, ou seja, não cobrados. Em contrapeso, a parte da pressão exercida sobre a balanço de pagamentos por tais medidas são aumentadas as tarifas sobre produtos manufaturados que já começaram a ser produzidos internamente, causando assim, uma alta de preços no setor interno.',
            'Desse modo, o autor concluiu que a alta dos preços e a baixa na renda per capita dessas economias sucede os fatores: da retração das importações pelo processo de substituição de importações; a deterioração dos termos de intercâmbio causada pela assimetria de valor monetário da moeda local com a moeda externa, sendo esta mais valiosa do que aquela; a expansão do crédito para o financiamento de estoques reguladores na temporada de alta produção a fim de manter  preço estável; e o aumento das tarifas de exportação; são o que determinou uma série de mudanças na estrutura de custos de produção, juntamente a esses fatores houve também a luta de vários grupos sociais em defesa de sua renda, resultando em modificações nos preços relativos e na distribuição de renda. O resultado no final foi de um aumento no nível geral de preços dos bens finais.'
        ],
        referece: 'FURTADO, C. Development and stagnation in Latin America: A structuralist approach. Studies in Comparative International Development, v. 1, n. 11, p. 159–175, nov. 1965.',
        review: 'Hugo Feitosa Gonçalves',
        imageUrl: 'https://082noticias.com/wp-content/uploads/2021/05/Celso-Furtado.jpg',
        caption: 'Imagen de Celso Furtado'
    },
    {
        title: 'DESENVOLVIMENTO E ESTAGNAÇÃO NA AMÉRICA LATINA: UMA ABORDAGEM ESTRUTURALISTA, POR CELSO FURTADO',
        category: 'Resenha',
        date: '2023-08-15',
         text: [
            'Em seu intitulado desenvolvimento e estagnação na América Latina, Celso Furtado busca compreender a partir de uma perspectiva estruturalista, como se deu historicamente o processo de estagnação do desenvolvimento das economias latino-americanas desde a forma como seus territórios foram colonizados até o modo em que buscaram a sua independência. Nesse sentido, o ponto-guia escolhido pelo autor do por que estudar esse tema dar-se-á por dois problemas: a tendência ao crescimento de preços nos produtos dessas economias e o decrescimento da renda per capita nas mesmas.',
            'Historicamente, o processo de colonização dos países latino-americanos foi sustentado por uma cadeia de núcleos urbanos melhor desenvolvidos e que buscavam em novas terras um lugar para auferirem ainda mais privilégios dentro de seu próprio espaço. Desse modo, os núcleos, por meio de concessões bem divididas dessas terras, àqueles que possuíam algum capital próprio para investirem na terra, principalmente em atividades agrícolas. Esses, agora proprietários da terra, após a abolição da escravatura, mantiveram em suas posses o modelo econômico chamado semifeudalismo, onde os servos produziam em suas terras e parte do que produziam era para sua própria subsistência por meio do aluguel de terras, e os seus donos exportavam os excedentes produzidos.',
            'Esse modelo semifeudal abriu brechas para o aparecimento de uma nova classe social oriunda daqueles que viram a oportunidade de lucrar por fora do setor agrário, contrabandeando pedras preciosas. Esses senhores tinham o interesse de exportá-las e dessa forma obterem seus ganhos, eles são o que a posteriori é compreendido como pré-capitalistas e tinham tendências à formação de centros urbanos, pois queriam que a terra se parecesse com o núcleo que a priori colonizou a terra.',
            'É importante notar que essas duas classes não são conflitantes apesar de tudo. Os latifundiários ocupavam-se da ordem no campo, tinham a propriedade em seu poder, possuíam o aluguel de terras, adicionados à créditos que possuíam para seus negócios advindos das metrópoles e núcleos que os dera as terras para investirem segundo seus interesses, enquanto àqueles que não tinham onde viver, trabalhavam para ter onde dormir e o que comer. Já os contrabandistas, beneficiavam-se da exportação de pedras e arrecadavam impostos sobre tais, pois com o aumento das oportunidades nas cidades, os trabalhadores saíam de suas terras a fim de melhores condições, lá encontram trabalho e os exportadores têm praticamente “mão de obra ilimitada” pelo fato de que, nos campos, quanto maior a família, mais trabalhadores.',
            'Com o surgimento do Estado próprio dessas colônias, há então a conformidade de interesses dessas duas classes. Os latifundiários querendo aumentar cada vez mais seus privilégios e direitos de propriedade, e os contrabandistas enfim legitimaram seus impérios sombrios com um novo nome: comerciantes.',
            'Logo após a introdução dos agentes, o autor descreve como se deu esse passo no setor exportador nos países latino-americanos. Sendo o que ele chama de: convergência de fatores exógenos e endógenos. Por endógenos, entende-se um fator que vem de dentro do território, ou seja, os metais e pedras minerados; as plantações; a pecuária etc. Já por exógenos, ele refere-se a fatores que surgem de fora, como os empréstimos concedidos pelas metrópoles. Nesse período, os latifundiários foram deixando de ser simplesmente representantes da Metrópole e passaram a ser uma instituição básica da estrutura social e política de suas próprias regiões. Ressalta-se que, em nenhum momento, os atores endógenos, latifundiários e comerciantes deixam de sobrepor os interesses da metrópole, pois esta é quem garantia a lucratividade para ambos.',
            'Ademais, o processo por trás da industrialização na América Latina ocorreu por meio da substituição de importações, onde a importação de determinados bens foi reduzida ou substituída no mercado interno por produtos produzidos internamente enquanto ampliou a importação de capital industrial afim do país obter meios pelos quais desenvolver a sua produção e deixar de exportar bens de menor valor agregado.',
            'Furtado deu o exemplo de: se um país, em 1929, possuía exportações que representavam cerca de 60% do fornecimento agregado de produtos manufaturados, com a redução dos preços de exportação, a capacidade de importação foi reduzida à 50%. Porém, sendo as exportações consistentes em produtos agrícolas e dizem respeito a um grande número de produtores, essa situação leva o governo a expandir o crédito para financiar a estocagem de excedentes agrícolas, bem como modificar a taxa de câmbio em favor dos exportadores de maneira a livrar o setor do excesso de oferta criado pela crise.',
            'Essas medidas permitiram que o nível de renda monetária do setor exportador tenho sido mantido estável e a demanda agregada ajustada a um nível maior de impostos concedidos, ou seja, não cobrados. Em contrapeso, a parte da pressão exercida sobre a balanço de pagamentos por tais medidas são aumentadas as tarifas sobre produtos manufaturados que já começaram a ser produzidos internamente, causando assim, uma alta de preços no setor interno.',
            'Desse modo, o autor concluiu que a alta dos preços e a baixa na renda per capita dessas economias sucede os fatores: da retração das importações pelo processo de substituição de importações; a deterioração dos termos de intercâmbio causada pela assimetria de valor monetário da moeda local com a moeda externa, sendo esta mais valiosa do que aquela; a expansão do crédito para o financiamento de estoques reguladores na temporada de alta produção a fim de manter  preço estável; e o aumento das tarifas de exportação; são o que determinou uma série de mudanças na estrutura de custos de produção, juntamente a esses fatores houve também a luta de vários grupos sociais em defesa de sua renda, resultando em modificações nos preços relativos e na distribuição de renda. O resultado no final foi de um aumento no nível geral de preços dos bens finais.'
        ],
        referece: 'FURTADO, C. Development and stagnation in Latin America: A structuralist approach. Studies in Comparative International Development, v. 1, n. 11, p. 159–175, nov. 1965.',
        review: 'Hugo Feitosa Gonçalves',
        imageUrl: 'https://082noticias.com/wp-content/uploads/2021/05/Celso-Furtado.jpg',
        caption: 'Imagen de Celso Furtado'
    },
    {
        title: 'DESENVOLVIMENTO E ESTAGNAÇÃO NA AMÉRICA LATINA: UMA ABORDAGEM ESTRUTURALISTA, POR CELSO FURTADO',
        category: 'Resenha',
        date: '2023-08-15',
         text: [
            'Em seu intitulado desenvolvimento e estagnação na América Latina, Celso Furtado busca compreender a partir de uma perspectiva estruturalista, como se deu historicamente o processo de estagnação do desenvolvimento das economias latino-americanas desde a forma como seus territórios foram colonizados até o modo em que buscaram a sua independência. Nesse sentido, o ponto-guia escolhido pelo autor do por que estudar esse tema dar-se-á por dois problemas: a tendência ao crescimento de preços nos produtos dessas economias e o decrescimento da renda per capita nas mesmas.',
            'Historicamente, o processo de colonização dos países latino-americanos foi sustentado por uma cadeia de núcleos urbanos melhor desenvolvidos e que buscavam em novas terras um lugar para auferirem ainda mais privilégios dentro de seu próprio espaço. Desse modo, os núcleos, por meio de concessões bem divididas dessas terras, àqueles que possuíam algum capital próprio para investirem na terra, principalmente em atividades agrícolas. Esses, agora proprietários da terra, após a abolição da escravatura, mantiveram em suas posses o modelo econômico chamado semifeudalismo, onde os servos produziam em suas terras e parte do que produziam era para sua própria subsistência por meio do aluguel de terras, e os seus donos exportavam os excedentes produzidos.',
            'Esse modelo semifeudal abriu brechas para o aparecimento de uma nova classe social oriunda daqueles que viram a oportunidade de lucrar por fora do setor agrário, contrabandeando pedras preciosas. Esses senhores tinham o interesse de exportá-las e dessa forma obterem seus ganhos, eles são o que a posteriori é compreendido como pré-capitalistas e tinham tendências à formação de centros urbanos, pois queriam que a terra se parecesse com o núcleo que a priori colonizou a terra.',
            'É importante notar que essas duas classes não são conflitantes apesar de tudo. Os latifundiários ocupavam-se da ordem no campo, tinham a propriedade em seu poder, possuíam o aluguel de terras, adicionados à créditos que possuíam para seus negócios advindos das metrópoles e núcleos que os dera as terras para investirem segundo seus interesses, enquanto àqueles que não tinham onde viver, trabalhavam para ter onde dormir e o que comer. Já os contrabandistas, beneficiavam-se da exportação de pedras e arrecadavam impostos sobre tais, pois com o aumento das oportunidades nas cidades, os trabalhadores saíam de suas terras a fim de melhores condições, lá encontram trabalho e os exportadores têm praticamente “mão de obra ilimitada” pelo fato de que, nos campos, quanto maior a família, mais trabalhadores.',
            'Com o surgimento do Estado próprio dessas colônias, há então a conformidade de interesses dessas duas classes. Os latifundiários querendo aumentar cada vez mais seus privilégios e direitos de propriedade, e os contrabandistas enfim legitimaram seus impérios sombrios com um novo nome: comerciantes.',
            'Logo após a introdução dos agentes, o autor descreve como se deu esse passo no setor exportador nos países latino-americanos. Sendo o que ele chama de: convergência de fatores exógenos e endógenos. Por endógenos, entende-se um fator que vem de dentro do território, ou seja, os metais e pedras minerados; as plantações; a pecuária etc. Já por exógenos, ele refere-se a fatores que surgem de fora, como os empréstimos concedidos pelas metrópoles. Nesse período, os latifundiários foram deixando de ser simplesmente representantes da Metrópole e passaram a ser uma instituição básica da estrutura social e política de suas próprias regiões. Ressalta-se que, em nenhum momento, os atores endógenos, latifundiários e comerciantes deixam de sobrepor os interesses da metrópole, pois esta é quem garantia a lucratividade para ambos.',
            'Ademais, o processo por trás da industrialização na América Latina ocorreu por meio da substituição de importações, onde a importação de determinados bens foi reduzida ou substituída no mercado interno por produtos produzidos internamente enquanto ampliou a importação de capital industrial afim do país obter meios pelos quais desenvolver a sua produção e deixar de exportar bens de menor valor agregado.',
            'Furtado deu o exemplo de: se um país, em 1929, possuía exportações que representavam cerca de 60% do fornecimento agregado de produtos manufaturados, com a redução dos preços de exportação, a capacidade de importação foi reduzida à 50%. Porém, sendo as exportações consistentes em produtos agrícolas e dizem respeito a um grande número de produtores, essa situação leva o governo a expandir o crédito para financiar a estocagem de excedentes agrícolas, bem como modificar a taxa de câmbio em favor dos exportadores de maneira a livrar o setor do excesso de oferta criado pela crise.',
            'Essas medidas permitiram que o nível de renda monetária do setor exportador tenho sido mantido estável e a demanda agregada ajustada a um nível maior de impostos concedidos, ou seja, não cobrados. Em contrapeso, a parte da pressão exercida sobre a balanço de pagamentos por tais medidas são aumentadas as tarifas sobre produtos manufaturados que já começaram a ser produzidos internamente, causando assim, uma alta de preços no setor interno.',
            'Desse modo, o autor concluiu que a alta dos preços e a baixa na renda per capita dessas economias sucede os fatores: da retração das importações pelo processo de substituição de importações; a deterioração dos termos de intercâmbio causada pela assimetria de valor monetário da moeda local com a moeda externa, sendo esta mais valiosa do que aquela; a expansão do crédito para o financiamento de estoques reguladores na temporada de alta produção a fim de manter  preço estável; e o aumento das tarifas de exportação; são o que determinou uma série de mudanças na estrutura de custos de produção, juntamente a esses fatores houve também a luta de vários grupos sociais em defesa de sua renda, resultando em modificações nos preços relativos e na distribuição de renda. O resultado no final foi de um aumento no nível geral de preços dos bens finais.'
        ],
        referece: 'FURTADO, C. Development and stagnation in Latin America: A structuralist approach. Studies in Comparative International Development, v. 1, n. 11, p. 159–175, nov. 1965.',
        review: 'Hugo Feitosa Gonçalves',
        imageUrl: 'https://082noticias.com/wp-content/uploads/2021/05/Celso-Furtado.jpg',
        caption: 'Imagen de Celso Furtado'
    },
]